version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Mkdoc install
          command: pip install mkdocs-material
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Doc
          command: mkdocs gh-deploy --force
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=FallenVaders_mc-fallenvaders
      - run:
          name: Test
          command: mvn test

workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud
