version: 2.1

environment:
  PIPENV_VENV_IN_PROJECT: true

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=FallenVaders_mc-fallenvaders
      - run:
          name: Test
          command: mvn test
  deploy-doc:
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run:
          name: Install Python and Pip
          command: |
            sudo apt update
            sudo apt install python3 python3-pip
      - run:
          name: Install MkDocs
          command: sudo pip install mkdocs-material
      - run:
          name: Deploy doc
          command: mkdocs gh-deploy --force

workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: gh-pages
          context: SonarCloud
      - deploy-doc:
          filters:
            branches:
              only: master
