version: 2.1

environment:
  PIPENV_VENV_IN_PROJECT: true

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - run:
          name: Doc
          command: |
            sudo apt install python3-pip
            sudo pip install mkdocs-material
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=FallenVaders_mc-fallenvaders
      - run:
          name: Test
          command: mvn test

workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud
