name: ${project.name}
version: ${project.version}
api-version: ${minecraft.api.version}
description: ${project.description}
depend: [ ProtocolLib ]
main: fr.fallenvaders.minecraft.mc_enhancer.McEnhancerPlugin
