name: ${project.name}
version: ${project.version}
api-version: ${minecraft.api.version}
description: ${project.description}
author: Glynix
main: ${project.groupId}.mini_events.MiniEventsPlugin

commands:
    event:
        permission: admin.event
        description: Gestion des événements.
