/*
 *  This file is part of the FallenVaders distribution (https://github.com/FallenVaders).
 *  Copyright © 2021 Loïc DUBOIS-TERMOZ.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 3.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package fr.fallenvaders.minecraft.test_server.deploy;

import org.jetbrains.annotations.NotNull;

import javax.inject.Singleton;
import java.util.StringJoiner;

/**
 * Assembler of the FallenVaders's plugin jar file name generated by Maven.
 *
 * @author Voltariuss
 * @since 0.3.0
 */
@Singleton
public class MavenPluginJarNameAssembler implements FVPluginJarNameAssembler {

  private static final String DELIMITER = "-";
  private static final String FILE_EXTENSION = ".jar";

  @Override
  @NotNull
  public String assemble(
      @NotNull String fvPluginJarCoreName,
      @NotNull String projectVersion,
      @NotNull String fvPluginJarComplementName) {
    StringJoiner sb = new StringJoiner(DELIMITER);
    sb.add(fvPluginJarCoreName);
    sb.add(projectVersion);
    sb.add(fvPluginJarComplementName);
    sb.add(FILE_EXTENSION);
    return sb.toString();
  }
}
